spring:
    datasource:
        url: jdbc:mysql://localhost:3306/gestiondeStock?creatIfNotExist=true
        username: root
        password : root
        driver-class-name: com.mysql.cj.jdbc.Driver
    # BDSM
    jpa:
        database: MYSQL
        show-sql: false
        # DDL auto (update, create, creat-drop) 
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect

server:
    port: 8081  